name: Build and Publish (LINUX/WINDOWS)

on:
  push:
    tags:
      - "v*"

jobs:
  # use a matrix to run on multiple platforms

  draft_release:
    permissions:
      contents: write
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 18

      - name: Install pnpm
        run: npm install -g pnpm

      - name: Install dependencies
        run: pnpm install

      - name: Build
        run: pnpm run build

      - name: Compile Artifacts And Create Draft Release
        uses: nick-fields/retry@v2
        with:
          timeout_minutes: 15
          max_attempts: 6
          retry_wait_seconds: 15
          retry_on: error
          shell: "bash"
          command: pnpm run publish:platform
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
